### ISSUE TITLE
左侧栏图标优化一下会更好

### ISSUE THREAD

**Issue by Ke-Shuo** [pinsoftstudio/SecondDownloader#1]
其实已经很好了，如果将“设置”图标放在底部会显得更酷些🤭
![QQ_1722434040680](https://github.com/user-attachments/assets/f733a86c-a963-4423-a22d-67b36783f1ea)

**Comment by ProgramCX** [comment]
你说的没错！马上我改一下。请问你觉得左侧栏再加一点什么内容好呢？

**Comment by Ke-Shuo** [comment]
可以再“设置”上面加个“反馈”按钮，这样便于你们更快集中处理BUG。

**Comment by ProgramCX** [comment]
可以。感谢你的反馈。问题解决了会第一时间通知你。

**Comment by ProgramCX** [comment]
你好。我已经根据你提出的建议进行更改。感谢你的反馈
![image](https://github.com/user-attachments/assets/8120be56-afa9-432f-b638-ff4671e0c87b)
