### ISSUE TITLE
UI问题

### ISSUE THREAD

**Issue by Ke-Shuo** [pinsoftstudio/SecondDownloader#2]
浅色主题下灰一块白一块的问题解决下
![QQ_1722583671652](https://github.com/user-attachments/assets/3729f772-49c4-46ae-927c-3cf8e6e4dd7f)

**Comment by ProgramCX** [comment]
哪一个？

**Comment by ProgramCX** [comment]
好的

**Comment by ProgramCX** [comment]
![image](https://github.com/user-attachments/assets/55b9891a-aea4-4eb4-ba52-75763545540c)
你反馈的问题已经解决，感谢你的反馈~
