### ISSUE TITLE
want to build on linux

### ISSUE THREAD

**Issue by nepvibes** [pinsoftstudio/SecondDownloader#4]
please add support for linux. i modified .pro files to build in linux but libDownload/../temp/bin/debug/libDialog.a: No such file or directory dialog library is not created

**Comment by ProgramCX** [comment]
Ok,I will.I have been doing lots of things theses days.You can build it on Windows.If you have any questions,please tell me.

**Comment by ProgramCX** [comment]
We will add support for linux after the release of 1.0.0.0 version.Thank you for your advice!

**Comment by ProgramCX** [comment]
We will add support for linux after the release of V.1.0.0.0.Thank you for your advice.

**Comment by ProgramCX** [comment]
We are refactoring the project on https://github.com/L-Super/FlowD  ,and it added support for linux.We are hoping that you commit to our new respository.

**Comment by nepvibes** [comment]
thank you. I can build that now but ui is in chinese now. let me check internals first and will follow in that repository now on.
